name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Lint HTML files with HTMLHint
        run: npx htmlhint "**/*.html" --config .htmlhintrc

      - name: Lint CSS files with Stylelint
        run: npx stylelint "**/*.css"

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the static website using Parcel
        run: npx parcel build src/index.html --out-dir dist --no-cache